### ISSUE TITLE
Install fails on Windows 10 (19045.3324)

### ISSUE THREAD

**Issue by rojas-claudio** [OverallLine5/MobileBandSync#15]
Installing certificates and running the .appxbundle results in the following error on Windows 10:

`App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)`

![image](https://github.com/OverallLine5/MobileBandSync/assets/71095411/99b05063-dd89-4d81-8b2f-a9359a905124)

**Comment by OverallLine5** [comment]
Hi, did you choose the DesktopBandSync_0.7.0.24_x86_x64_arm.cer file? If it doesn't work, try installing it to a different cert storage.

**Comment by rojas-claudio** [comment]
Still no luck. Could it be because the certificate is expired? It's telling me it was only valid from 10/22/2021 to 10/22/2022.

**Comment by oliverhildner** [comment]
Also no luck for me. DesktopBandSync_0.7.0.24_x86_x64_arm.cer file seems to be expired. 
the loeselcom.cer file is not expired but it also doesn't work.
I tried installing it as recommended by Windows, but also under "Vertrauenswürdige Stammzertifizierungsstellen" and "Vertrauenswürdige Personen", which both did not work. 
![grafik](https://github.com/OverallLine5/MobileBandSync/assets/50845166/6f76991f-b022-480f-9d4e-88d97c229c9a)

Am I missing something? I would love this to work.

**Comment by OverallLine5** [comment]
Sorry für that, didn't recognize that the certificate became invalid. I'm syncing with my W10M device and didn't expect anyone else to use the device besides me 😂 I will have to set up my environment first before I can build a new version of DesktopBandSync. Hopefully next week - stay tuned!

**Comment by oliverhildner** [comment]
Thank you for that. I am looking for something like this for years to use my Band 2 again and I am really looking forward to try it :)

**Comment by OverallLine5** [comment]
Added v0.7.1, should be installable again.
