### ISSUE TITLE
Support for Windows 10

### ISSUE THREAD

**Issue by dvidebaek** [OverallLine5/MobileBandSync#8]
Hi,
When im trying to install det MSIXbundle i get this error. Your package is build to only support Windows 11. Could you lower your package requirement, so windows 10 user also can use this app. Im on Windows 10 21H1 build 19044.1387.

The error im getting:
"Windows cannot install package MobileBandSync_0.5.2.24_x64__71s09sxc11tx2 because this package is not compatible with the device. The package requires OS version 10.0.22000.0 or higher on the Windows.Universal device family. The device is currently running OS version 10.0.19044.1387. (0x80073cfd)"

**Comment by OverallLine5** [comment]
Good catch :-) I migrated the desktop project to VS2022 and didn't realize that the target platform was automatically modified to Win 11.  Please try again with v0.5.4, this pre-release also adds filtering.

**Comment by dvidebaek** [comment]
Cheers! Finally I can use my Band again. :-)

**Comment by OverallLine5** [comment]
Have fun! Great to see that I'm not the only one who is still using the Band :-)
